# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: upkeep.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'upkeep.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cupkeep.proto\x12\x06upkeep\"3\n\x19UpdateOpenAiApiKeyRequest\x12\x16\n\x0eopenai_api_key\x18\x01 \x01(\t\"3\n\x1aUpdateOpenAiApiKeyResponse\x12\x15\n\rtest_response\x18\x01 \x01(\t\"\x98\x01\n\x1fUpdateCompletionsHeadersRequest\x12\x45\n\x07headers\x18\x01 \x03(\x0b\x32\x34.upkeep.UpdateCompletionsHeadersRequest.HeadersEntry\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x9a\x01\n UpdateCompletionsHeadersResponse\x12\x46\n\x07headers\x18\x01 \x03(\x0b\x32\x35.upkeep.UpdateCompletionsHeadersResponse.HeadersEntry\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xd4\x01\n\x06Upkeep\x12]\n\x12UpdateOpenAiApiKey\x12!.upkeep.UpdateOpenAiApiKeyRequest\x1a\".upkeep.UpdateOpenAiApiKeyResponse\"\x00\x12k\n\x14\x41\x64\x64\x43ompletionsHeader\x12\'.upkeep.UpdateCompletionsHeadersRequest\x1a(.upkeep.UpdateCompletionsHeadersResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'upkeep_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPDATECOMPLETIONSHEADERSREQUEST_HEADERSENTRY']._loaded_options = None
  _globals['_UPDATECOMPLETIONSHEADERSREQUEST_HEADERSENTRY']._serialized_options = b'8\001'
  _globals['_UPDATECOMPLETIONSHEADERSRESPONSE_HEADERSENTRY']._loaded_options = None
  _globals['_UPDATECOMPLETIONSHEADERSRESPONSE_HEADERSENTRY']._serialized_options = b'8\001'
  _globals['_UPDATEOPENAIAPIKEYREQUEST']._serialized_start=24
  _globals['_UPDATEOPENAIAPIKEYREQUEST']._serialized_end=75
  _globals['_UPDATEOPENAIAPIKEYRESPONSE']._serialized_start=77
  _globals['_UPDATEOPENAIAPIKEYRESPONSE']._serialized_end=128
  _globals['_UPDATECOMPLETIONSHEADERSREQUEST']._serialized_start=131
  _globals['_UPDATECOMPLETIONSHEADERSREQUEST']._serialized_end=283
  _globals['_UPDATECOMPLETIONSHEADERSREQUEST_HEADERSENTRY']._serialized_start=237
  _globals['_UPDATECOMPLETIONSHEADERSREQUEST_HEADERSENTRY']._serialized_end=283
  _globals['_UPDATECOMPLETIONSHEADERSRESPONSE']._serialized_start=286
  _globals['_UPDATECOMPLETIONSHEADERSRESPONSE']._serialized_end=440
  _globals['_UPDATECOMPLETIONSHEADERSRESPONSE_HEADERSENTRY']._serialized_start=237
  _globals['_UPDATECOMPLETIONSHEADERSRESPONSE_HEADERSENTRY']._serialized_end=283
  _globals['_UPKEEP']._serialized_start=443
  _globals['_UPKEEP']._serialized_end=655
# @@protoc_insertion_point(module_scope)
